fix various issues with check_rdiff_log nagios plugin

diff --git a/files/default/nagios/plugins/check_rdiff_log b/files/default/nagios/plugins/check_rdiff_log
--- a/files/default/nagios/plugins/check_rdiff_log
+++ b/files/default/nagios/plugins/check_rdiff_log
@@ -2,18 +2,31 @@
 
 read -d ' ' -a JOBS <<< "`ls /home/rdiff-backup-server/scripts`" # Array of all jobs
 
+# Note: We manage the failure of new jobs differently than the failure of other
+# jobs because the rdiff-backup cookbook does not create Nagios checks for jobs
+# until after their first run (because otherwise it would just be critical
+# because the repo doesn't exist yet).  If a normal job fails, this check will
+# still return OK status because the job already has its own check that will
+# send a CRITICAL alert.  In this case, this check simply serves as a basic
+# "overview" check, and the job-specific check for any normal failed jobs (or
+# the logs) should be consulted for details).  This check only returns CRITICAL
+# status if a purge or a job that doesn't already have a Nagios check (i.e. a
+# new job on its first run).  Purges are not differentiated because none of
+# them have their own Nagios check, and so every failed purge is worth
+# reporting a CRITICAL status for.
+
 # Backup jobs
-TOTAL=${#JOBS[@]}
-SUCC=0
-NORMFAIL=0
-FIRSTFAIL=0
-MISSING=0
+TOTAL=${#JOBS[@]}   # Total number of jobs
+SUCC=0              # Number of jobs whose last run succeeded.
+NORMFAIL=0          # Number of existing jobs (that already have Nagios checks) whose last run failed.
+FIRSTFAIL=0         # Number of new jobs (that do not already have Nagios checks) whose first/last run failed.
+MISSING=0           # Number of jobs that did not finish at all (or were never run).
 
 # Purges
-PTOTAL=${#JOBS[@]}
-PSUCC=0
-PFAIL=0
-PMISSING=0
+PTOTAL=${#JOBS[@]}  # Total number of purges
+PSUCC=0             # Number of jobs whose last purge succeeded.
+PFAIL=0             # Number of jobs whose last purge failed.
+PMISSING=0          # Number of jobs whose last purge did not finish at all.
 
 LOGS=`ls /var/log/rdiff-backup/general/* | tail -n 2 | xargs` # Last 2 logs
 
@@ -52,16 +65,6 @@ MESSAGE="$SUCC/$TOTAL backup(s) succeeded"
 if [ $TOTAL -eq $SUCC -a $PTOTAL -eq $PSUCC ]; then
   STATUS="OK:"
 fi
-
-# Backup jobs
-if [ $MISSING -ne 0 ]; then
-  STATUS="WARNING:"
-  MESSAGE="${MESSAGE}; $MISSING backup(s) are missing ( "
-  for MISSINGJOB in ${MISSINGJOBS[@]}; do
-    MESSAGE="${MESSAGE}${MISSINGJOB} "
-  done
-  MESSAGE="${MESSAGE})"
-fi
 if [ $NORMFAIL -ne 0 ]; then
   STATUS="OK:"
   MESSAGE="${MESSAGE}; $NORMFAIL existing backup(s) failed ( "
@@ -70,21 +73,27 @@ if [ $NORMFAIL -ne 0 ]; then
   done
   MESSAGE="${MESSAGE})"
 fi
-if [ $FIRSTFAIL -ne 0 ]; then
-  STATUS="CRITICAL:"
-  MESSAGE="${MESSAGE}; $FIRSTFAIL first backup(s) failed ( "
-  for FIRSTFAILJOB in ${FIRSTFAILJOBS[@]}; do
-    MESSAGE="${MESSAGE}${FIRSTFAILJOB} "
+if [ $MISSING -ne 0 ]; then
+  STATUS="WARNING:"
+  MESSAGE="${MESSAGE}; $MISSING backup(s) are missing ( "
+  for MISSINGJOB in ${MISSINGJOBS[@]}; do
+    MESSAGE="${MESSAGE}${MISSINGJOB} "
   done
   MESSAGE="${MESSAGE})"
 fi
-
-# Purges
 if [ $PMISSING -ne 0 ]; then
   STATUS="WARNING:"
   MESSAGE="${MESSAGE}; $PMISSING purge(s) are missing ( "
   for PMISSINGJOB in ${PMISSINGJOBS[@]}; do
     MESSAGE="${MESSAGE}${PMISSINGJOB} "
+  done
+  MESSAGE="${MESSAGE})"
+fi
+if [ $FIRSTFAIL -ne 0 ]; then
+  STATUS="CRITICAL:"
+  MESSAGE="${MESSAGE}; $FIRSTFAIL first backup(s) failed ( "
+  for FIRSTFAILJOB in ${FIRSTFAILJOBS[@]}; do
+    MESSAGE="${MESSAGE}${FIRSTFAILJOB} "
   done
   MESSAGE="${MESSAGE})"
 fi
@@ -102,6 +111,8 @@ if [ $STATUS = "OK:" ]; then
   exit 0
 elif [ $STATUS = "WARNING:" ]; then
   exit 1
-else
+elif [ $STATUS = "CRITICAL:" ]; then
   exit 2
+else
+  exit 3
 fi
